### ISSUE TITLE
Hi! 求助Dubbox与swagger集成

### ISSUE THREAD

**Issue by kiaklu** [liaodongd/dd#1]
你好，最近遇到的大难题。可以分享下“gongzf的两篇swagger文章 dubbox swagger 学习 dubbox项目集成swagger”这两篇文章吗，现在十分需要，谢谢了！

**Comment by kiaklu** [comment]
请问文章里面的说的“方法是修改了swagger-jaxrs包的源码以适配dubbox”，你知道是怎么做的吗？

**Comment by liaodongd** [comment]
测试随便传的文件没想到也有人看23333 貌似修改了AcceptHeaderApiListingResource 你对比一下吧

**Comment by kiaklu** [comment]
好的，非常感谢。这些文件和包是你自己写的吗

**Comment by kiaklu** [comment]
你有demo工程吗？

**Comment by liaodongd** [comment]
两篇文档和包是同事负责研究的，我之前直接集成到项目里了没有demo

**Comment by kiaklu** [comment]
我按文章的步骤集成有还是有问题，你可以把如何配置和集成和我说下吗，QQ991969344

**Comment by kiaklu** [comment]
看一下你web.xml和dubbox是怎么配的，可能是我配置有问题
